GET http://localhost:3003/api/users

###

GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9vbiBzYWxhdHR1IiwiaWQiOiI1ZjQ3Y2RiYjJkYzA2MTM5OTQ3Y2ZlN2IiLCJpYXQiOjE1OTg1NDEyOTN9.U2Ow1iIvC591UyAGoe8NoNFiReMjcBNlTU1XUTAs5Ak
Content-Type: application/json

{
  "title": "Kauheaa! Kissa jäi auton alle",
  "author": "Kiva Blogaaja",
  "url": "www.kivatblogit.fi",
  "likes": 3
}

###

POST http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pa8OkIHNhdHR1bWEiLCJpZCI6IjVmNDdjZGM1MmRjMDYxMzk5NDdjZmU3YyIsImlhdCI6MTU5ODU0MTMzNX0.EvdME1Wsry4xbdh1RjgQu0rRNfTcwgkGCOqMNfXbUP8
Content-Type: application/json

{
  "title": "Jes! Kissa jäi auton alle",
  "author": "Ilkeä Blogaaja",
  "url": "www.ilkeätblogit.fi",
  "likes": 3
}

###

POST http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9vbiBzYWxhdHR1IiwiaWQiOiI1ZjQ3Y2RiYjJkYzA2MTM5OTQ3Y2ZlN2IiLCJpYXQiOjE1OTg1NDEyOTN9.U2Ow1iIvC591UyAGoe8NoNFiReMjcBNlTU1XUTAs5Ak
Content-Type: application/json

{
  "title": "Mikä sydämetön ilkimys!",
  "author": "Haluaa haukkua",
  "url": "www.haukkumisblogit.fi",
  "likes": 999
}

###

POST http://localhost:3003/api/blogs
Authorization: bearer MENIRIKKI
Content-Type: application/json

{
  "title": "Mikä sydämetön ilkimys!",
  "author": "Haluaa haukkua",
  "url": "www.haukkumisblogit.fi",
  "likes": 999
}

###

DELETE http://localhost:3003/api/blogs/5f47c2b417ce3415b4f4ee6e
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9vbiBzYWxhdHR1IiwiaWQiOiI1ZjQ2NmFjMjFmMzUwZjQ3NjA4ZmI5NmQiLCJpYXQiOjE1OTg1MzcyODB9.duM0XKZ4ylPzz0WIJHtnSStB9vtxH1FEW4q051gfFSE
Content-Type: application/json

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "oon salattu",
  "password": "very secret",
  "name": "Lol Salattu"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Mikä sattuma",
  "password": "(・。・)",
  "name": "Minäkin Olen Salattu"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Me",
  "password": "(・。・)",
  "name": "..."
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Paras salasana ikinä",
  "password": "ツ",
  "name": "hah"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "oon salattu",
  "password": "very secret"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "Mikä sattuma",
  "password": "(・。・)"
}

###

DELETE http://localhost:3003/api/blogs/5f47d34f14a2b51d2cea136e
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9vbiBzYWxhdHR1IiwiaWQiOiI1ZjQ3Y2RiYjJkYzA2MTM5OTQ3Y2ZlN2IiLCJpYXQiOjE1OTg1NDIxNDV9.CD8dH8I8oO3hnyK_4lEhVoBQvY0jktRI_tVkoUYwmss
Content-Type: application/json
