DELETE http://localhost:3001/api/persons/7

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "a",
  "number": "2"
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "d",
  "number": "4"
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "2"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "fdsa",
  "number": ""
}